# Generated by Django 4.0.1 on 2022-02-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contactdate', models.DateField()),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='OauthToken',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('oauth_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('oauth_token_secret', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
