# Generated by Django 4.0.1 on 2022-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtokentemp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='oauthtokentemp',
            constraint=models.UniqueConstraint(fields=('id', 'oauth_token', 'oauth_token_secret'), name='oauth_unique'),
        ),
    ]
