# Generated by Django 4.0.1 on 2022-02-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtokentemp',
            name='description',
        ),
    ]
