# Generated by Django 4.0.1 on 2022-02-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('acccess_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('access_token_secret', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OauthToken',
        ),
    ]
